#!/bin/sh
exec /usr/bin/env -i \
  PATH=/usr/bin:/bin \
  GIT_NO_REPLACE_OBJECTS=1 \
  /usr/bin/git \
  -c core.fsmonitor=false \
  -c core.ignoreStat=false \
  -c core.abbrev=8 \
  -c core.hooksPath=/dev/null \
  -c diff.external= \
  -c diff.trustExitCode=false \
  "$@"
