#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
METADATA_FILE="$ROOT_DIR/packaging/app_metadata.env"
TMP_ROOT="$ROOT_DIR/.tmp"
XCODE_WORKSPACE_RELATIVE=".swiftpm/xcode/package.xcworkspace"
XCODE_SCHEME="${SOLOPM_XCODE_SCHEME:-SoloPM}"
XCODE_DESTINATION="${SOLOPM_XCODE_DESTINATION:-platform=macOS}"
XCODE_CONFIGURATION="${SOLOPM_XCODE_CONFIGURATION:-Debug}"
AUTOMATED_PREFLIGHT_EVIDENCE_FILE="${SOLOPM_AUTOMATED_PREFLIGHT_EVIDENCE_FILE:-}"
REFRESH_MANUAL_HELPERS="${SOLOPM_REFRESH_MANUAL_HELPERS:-1}"
APP_NAME="SoloPM"
RUNTIME_AX_SMOKE_OUTPUT=""
VOICEOVER_CANDIDATE_SOURCE_COMMIT=""
VOICEOVER_CANDIDATE_PROJECT_ID=""
VOICEOVER_CANDIDATE_DATABASE=""
VOICEOVER_CANDIDATE_SELECTED_DESTINATION=""

if [[ -f "$METADATA_FILE" ]]; then
  # shellcheck source=/dev/null
  source "$METADATA_FILE"
fi

APP_NAME="${APP_NAME:-SoloPM}"
cd "$ROOT_DIR"

default_automated_preflight_evidence_file() {
  local commit
  commit="$(git rev-parse --short HEAD 2>/dev/null || true)"

  if [[ -z "${commit//[[:space:]]/}" ]]; then
    printf ".tmp/automated-release-preflight.md"
  else
    printf ".tmp/automated-release-preflight-${commit}.md"
  fi
}

if [[ -z "$AUTOMATED_PREFLIGHT_EVIDENCE_FILE" ]]; then
  # Release readiness auto-discovers this exact path, so the standard sweep
  # writes reusable proof instead of forcing operators to run the heavy gates
  # a second time just to produce evidence.
  AUTOMATED_PREFLIGHT_EVIDENCE_FILE="$(default_automated_preflight_evidence_file)"
fi

mkdir -p "$TMP_ROOT"
TMP_DIR="$(mktemp -d "$TMP_ROOT/solopm-automated-release-preflight.XXXXXX")"
MCP_EVIDENCE_FILE="$TMP_DIR/mcp-inspector.md"

section() {
  printf "\n== %s ==\n" "$1"
}

require_clean_source_tree_for_evidence() {
  if [[ -z "$AUTOMATED_PREFLIGHT_EVIDENCE_FILE" ]]; then
    return 0
  fi

  if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    echo "BLOCKER: automated preflight evidence requires a git worktree" >&2
    exit 2
  fi

  if ! git diff --quiet -- . || ! git diff --cached --quiet -- .; then
    echo "BLOCKER: automated preflight evidence requires a clean tracked source tree" >&2
    exit 2
  fi
}

tracked_source_tree_is_clean() {
  git rev-parse --is-inside-work-tree >/dev/null 2>&1 &&
    git diff --quiet -- . &&
    git diff --cached --quiet -- .
}

refresh_manual_release_helpers() {
  if [[ "$REFRESH_MANUAL_HELPERS" != "1" ]]; then
    echo "INFO: manual release helper refresh skipped because SOLOPM_REFRESH_MANUAL_HELPERS is not 1"
    return 0
  fi

  if ! tracked_source_tree_is_clean; then
    echo "INFO: manual release helper refresh skipped because tracked source tree is not clean"
    return 0
  fi

  ./script/prepare_release_manual_helpers.sh
}

write_automated_preflight_evidence() {
  if [[ -z "$AUTOMATED_PREFLIGHT_EVIDENCE_FILE" ]]; then
    return 0
  fi

  local evidence_file="$AUTOMATED_PREFLIGHT_EVIDENCE_FILE"
  if [[ "$evidence_file" != /* ]]; then
    evidence_file="$ROOT_DIR/$evidence_file"
  fi

  local evidence_dir generated_at source_commit
  evidence_dir="$(dirname "$evidence_file")"
  mkdir -p "$evidence_dir"
  generated_at="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  source_commit="$(git rev-parse --short HEAD 2>/dev/null || printf "unknown")"

  cat > "$evidence_file" <<EOF
# Automated Release Preflight Evidence

Status: passed
Generated by: script/check_automated_release_preflight.sh
Generated at: $generated_at
Source commit: $source_commit
Tracked source tree: clean
App: $APP_NAME
Xcode workspace: $XCODE_WORKSPACE_RELATIVE
Xcode scheme: $XCODE_SCHEME
Xcode configuration: $XCODE_CONFIGURATION
Xcode destination: $XCODE_DESTINATION
VoiceOver candidate source commit: $VOICEOVER_CANDIDATE_SOURCE_COMMIT
VoiceOver candidate project ID: $VOICEOVER_CANDIDATE_PROJECT_ID
VoiceOver candidate database: $VOICEOVER_CANDIDATE_DATABASE
VoiceOver candidate selected destination: $VOICEOVER_CANDIDATE_SELECTED_DESTINATION

## Passed Gates

- Release CI: passed
- Local CRUD smoke: passed
- Runtime accessible CRUD smoke: passed
- Layout stability smoke: passed
- Xcode build preflight: passed
- Launch preflight: passed
- Runtime accessibility preflight: passed
- MCP compliance preflight: passed

## Runtime AX Smoke

Runtime AX smoke: $RUNTIME_AX_SMOKE_OUTPUT

## Boundaries

- This does not mark the release ready.
- Manual VoiceOver evidence remains separate.
- Competitor hands-on evidence remains separate.
- Developer ID signing, notarization, Sparkle, Gatekeeper, and clean-environment evidence remain separate.
EOF

  printf "Automated release preflight evidence written to %s\n" "$evidence_file"
}

capture_voiceover_candidate_context() {
  local launch_env_file="$ROOT_DIR/.tmp/voiceover-review/launch.env"

  if [[ ! -f "$launch_env_file" ]]; then
    echo "BLOCKER: VoiceOver candidate launch env was not generated: $launch_env_file" >&2
    exit 2
  fi

  # Source the generated launch env instead of re-deriving values so the evidence
  # records the exact seeded candidate used by the runtime AX smoke gate.
  # shellcheck source=/dev/null
  source "$launch_env_file"
  VOICEOVER_CANDIDATE_SOURCE_COMMIT="${SOLOPM_VOICEOVER_REVIEW_SOURCE_COMMIT:-}"
  VOICEOVER_CANDIDATE_PROJECT_ID="${SOLOPM_VOICEOVER_REVIEW_PROJECT_ID:-}"
  VOICEOVER_CANDIDATE_DATABASE="${SOLOPM_DATABASE_PATH:-}"
  VOICEOVER_CANDIDATE_SELECTED_DESTINATION="${SOLOPM_PROJECT_BOARD_SELECTED_DESTINATION:-}"

  if [[ -z "${VOICEOVER_CANDIDATE_SOURCE_COMMIT//[[:space:]]/}" ||
    -z "${VOICEOVER_CANDIDATE_PROJECT_ID//[[:space:]]/}" ||
    -z "${VOICEOVER_CANDIDATE_DATABASE//[[:space:]]/}" ||
    -z "${VOICEOVER_CANDIDATE_SELECTED_DESTINATION//[[:space:]]/}" ]]; then
    echo "BLOCKER: VoiceOver candidate launch env is missing source/project/database/destination context" >&2
    exit 2
  fi
}

terminate_app() {
  local quit_pid=""

  /usr/bin/osascript -e "tell application \"$APP_NAME\" to quit" >/dev/null 2>&1 &
  quit_pid=$!

  for _ in {1..30}; do
    if ! kill -0 "$quit_pid" >/dev/null 2>&1; then
      wait "$quit_pid" >/dev/null 2>&1 || true
      break
    fi
    sleep 0.1
  done

  if kill -0 "$quit_pid" >/dev/null 2>&1; then
    kill "$quit_pid" >/dev/null 2>&1 || true
    wait "$quit_pid" >/dev/null 2>&1 || true
  fi

  pkill -x "$APP_NAME" >/dev/null 2>&1 || true
}

cleanup() {
  terminate_app
  rm -rf "$TMP_DIR"
}
trap cleanup EXIT

require_clean_source_tree_for_evidence

section "Release CI"
SOLOPM_CI_RELEASE_GATES=1 ./scripts/ci.sh

section "Local CRUD smoke"
./script/check_local_crud_smoke.sh

section "Runtime accessible CRUD smoke"
./script/check_runtime_accessible_crud_smoke.sh

section "Layout stability smoke"
./script/check_layout_stability_smoke.sh

section "Xcode build preflight"
if ! command -v xcodebuild >/dev/null 2>&1; then
  echo "BLOCKER: xcodebuild is required for the automated release preflight" >&2
  exit 2
fi
if [[ ! -d "$ROOT_DIR/$XCODE_WORKSPACE_RELATIVE" ]]; then
  echo "BLOCKER: missing SwiftPM Xcode workspace: $XCODE_WORKSPACE_RELATIVE" >&2
  exit 2
fi
xcodebuild \
  -workspace "$ROOT_DIR/$XCODE_WORKSPACE_RELATIVE" \
  -scheme "$XCODE_SCHEME" \
  -configuration "$XCODE_CONFIGURATION" \
  -destination "$XCODE_DESTINATION" \
  build

section "Launch preflight"
./script/build_and_run.sh --verify

section "Runtime accessibility candidate"
./script/prepare_voiceover_review_candidate.sh --skip-build --no-launch
capture_voiceover_candidate_context

section "Runtime accessibility preflight"
set +e
runtime_accessibility_output="$(./script/check_accessibility_preflight.sh --runtime --launch-env .tmp/voiceover-review/launch.env 2>&1)"
runtime_accessibility_status=$?
set -e
if [[ -n "$runtime_accessibility_output" ]]; then
  printf "%s\n" "$runtime_accessibility_output"
fi
if [[ "$runtime_accessibility_status" -ne 0 ]]; then
  exit "$runtime_accessibility_status"
fi
if ! RUNTIME_AX_SMOKE_OUTPUT="$(printf "%s\n" "$runtime_accessibility_output" | awk '/^OK: runtime AX smoke visible/ { print; found = 1; exit } END { if (found != 1) { exit 1 } }')"; then
  echo "BLOCKER: runtime accessibility preflight did not emit a runtime AX smoke OK line" >&2
  exit 1
fi
if [[ -z "${RUNTIME_AX_SMOKE_OUTPUT//[[:space:]]/}" ]]; then
  echo "BLOCKER: runtime accessibility preflight did not emit a runtime AX smoke OK line" >&2
  exit 1
fi

section "MCP compliance preflight"
SOLOPM_MCP_EVIDENCE_FILE="$MCP_EVIDENCE_FILE" ./script/verify_mcp_compliance.sh

section "Refresh manual release helpers"
refresh_manual_release_helpers

write_automated_preflight_evidence

printf "\nOK: automated release preflight passed\n"
printf "This does not mark the release ready.\n"
if [[ -n "$AUTOMATED_PREFLIGHT_EVIDENCE_FILE" ]]; then
  printf "NEXT: run "
  printf 'SOLOPM_AUTOMATED_PREFLIGHT_EVIDENCE_FILE=%q ./script/release_readiness_report.sh' "$AUTOMATED_PREFLIGHT_EVIDENCE_FILE"
  printf " to reuse this evidence with the remaining release blockers.\n"
else
  printf "NEXT: run SOLOPM_AUTOMATED_PROOF_GATES=1 ./script/release_readiness_report.sh to combine automated proof gates with the remaining release blockers.\n"
fi
printf "NEXT: complete manual VoiceOver, competitor hands-on, and signing/notarization/Sparkle/Gatekeeper evidence before release.\n"
