#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CI_ARTIFACT_ROOT="$ROOT_DIR/.tmp/ci-artifacts"

cd "$ROOT_DIR"

# Complete CI publishes reusable evidence, so caller-provided helper paths
# cannot replace the checked-in AX probes or SQLite implementation.
unset \
  SQLITE3 \
  AX_HELPERS \
  AX_TEXT_INPUT_HELPER \
  AX_SCROLL_HELPER \
  AX_BUTTON_HELPER \
  AX_MARKER_HELPER \
  AX_FRAME_HELPER \
  AX_PRESS_ELEMENT_HELPER \
  AX_RESIZE_WINDOW_HELPER \
  AX_IDENTIFIER_COUNT_HELPER \
  WINDOW_CONTENT_SIZE_HELPER \
  GIT_DIR \
  GIT_WORK_TREE \
  GIT_COMMON_DIR \
  GIT_INDEX_FILE \
  GIT_OBJECT_DIRECTORY \
  GIT_ALTERNATE_OBJECT_DIRECTORIES \
  GIT_SHALLOW_FILE \
  GIT_NAMESPACE \
  GIT_REPLACE_REF_BASE \
  GIT_CONFIG_PARAMETERS \
  GIT_CONFIG_COUNT \
  GIT_EXEC_PATH \
  GIT_EXTERNAL_DIFF \
  GIT_DIFF_OPTS
export GIT_NO_REPLACE_OBJECTS=1
export GIT_CONFIG_GLOBAL=/dev/null
export GIT_CONFIG_SYSTEM=/dev/null
export GIT_CONFIG_NOSYSTEM=1
export PATH="$ROOT_DIR/ci/trusted-bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin:/usr/local/bin:$PATH"

env \
  -u SUISUI_SWIFTPM_TEST_BASELINE_FILE \
  -u SUISUI_SWIFTPM_MAX_SKIPPED_FILE \
  ./ci/run-full.sh
env \
  -u SUISUI_RUNTIME_ACCESSIBLE_CRUD_RECOVERABLE_ONLY \
  -u SUISUI_LAYOUT_STABILITY_FRAME_DELTA_THRESHOLD_PX \
  -u SUISUI_LAYOUT_STABILITY_CLIPPING_TOLERANCE_PX \
  -u SUISUI_LAYOUT_STABILITY_DATABASE_PATH \
  -u SUISUI_HEADER_LAYOUT_DATABASE_PATH \
  -u SUISUI_HEADER_LAYOUT_ENTRYPOINTS_ONLY \
  -u SUISUI_LAYOUT_STABILITY_CONTENT_MIN_HEIGHT \
  -u SUISUI_LAYOUT_STABILITY_WINDOW_BELOW_MIN_WIDTH \
  -u SUISUI_LAYOUT_STABILITY_WINDOW_COMPACT_WIDTH \
  -u SUISUI_LAYOUT_STABILITY_WINDOW_CANONICAL_WIDTH \
  -u SUISUI_LAYOUT_STABILITY_WINDOW_MIN_WIDTH \
  -u SUISUI_LAYOUT_STABILITY_WINDOW_BELOW_MIN_HEIGHT \
  -u SUISUI_LAYOUT_STABILITY_WINDOW_MIN_HEIGHT \
  -u SUISUI_LAYOUT_STABILITY_WINDOW_STANDARD_WIDTH \
  -u SUISUI_LAYOUT_STABILITY_WINDOW_STANDARD_HEIGHT \
  -u SUISUI_LAYOUT_STABILITY_WINDOW_WIDE_WIDTH \
  -u SUISUI_LAYOUT_STABILITY_WINDOW_WIDE_HEIGHT \
  -u SUISUI_RUNTIME_TODAY_MAX_TOOLBAR_LAYOUT_DEPTH \
  -u SUISUI_RUNTIME_TODAY_WINDOW_WIDTH \
  -u SUISUI_RUNTIME_TODAY_WINDOW_HEIGHT \
  SUISUI_CI_COMPLETE_RUNTIME=1 \
  SUISUI_RUNTIME_POLICY=public-alpha \
  SUISUI_CI_ARTIFACT_ROOT="$CI_ARTIFACT_ROOT" \
  ./scripts/ci.sh ui-runtime
env \
  -u SUISUI_CI_VISUAL_GATE_LOCALE \
  -u SUISUI_VISUAL_SOURCE_REF \
  -u SUISUI_VISUAL_FIXTURE_SEEDER_BIN \
  -u SUISUI_AX_AUDIT_RESULT \
  -u SUISUI_VISUAL_CURRENT_SOURCE_COMMIT \
  -u SUISUI_VISUAL_BASELINE_VIEWPORT \
  -u SUISUI_SETTINGS_VISUAL_BASELINE_VIEWPORT \
  -u SUISUI_VOICE_COMMAND_VISUAL_BASELINE_VIEWPORT \
  -u SUISUI_VISUAL_EVIDENCE_REFERENCE_INSTANT \
  -u SUISUI_VISUAL_EVIDENCE_TIME_ZONE \
  -u SUISUI_VISUAL_EVIDENCE_LOCALE_IDENTIFIER \
  -u SUISUI_VISUAL_EVIDENCE_SCHEDULE_MODE \
  -u SUISUI_VISUAL_EVIDENCE_STABLE_BACKDROP \
  -u SUISUI_VISUAL_EVIDENCE_SYSTEM_APPEARANCE \
  -u SUISUI_UI_EVIDENCE_TARGET_TIMEOUT_SECONDS \
  -u SUISUI_UI_EVIDENCE_AX_MAX_NODES \
  SUISUI_CI_VISUAL_BASELINE_PROFILE=local-display \
  SUISUI_RUNTIME_POLICY=public-alpha \
  SUISUI_CI_ARTIFACT_ROOT="$CI_ARTIFACT_ROOT" \
  ./scripts/ci.sh ui-visual
env \
  -u SUISUI_PERFORMANCE_PROFILE \
  -u SUISUI_PERFORMANCE_BUILD_CONFIGURATION \
  -u SUISUI_PERFORMANCE_MAX_COLD_LAUNCH_MS \
  -u SUISUI_PERFORMANCE_MAX_DESTINATION_SWITCH_MS \
  -u SUISUI_PERFORMANCE_USE_PREBUILT_APP \
  -u SUISUI_PERFORMANCE_DATABASE_PATH \
  SUISUI_RUNTIME_POLICY=public-alpha \
  SUISUI_CI_ARTIFACT_ROOT="$CI_ARTIFACT_ROOT" \
  ./scripts/ci.sh ui-performance
